name: Contributor assistant | Signatures
description: An action to handle the Contributor License Agreement (CLA) or any other document
author: SAP
branding:
  icon: feather
  color: blue
inputs:
  GITHUB_TOKEN:
    description: "GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow. Paste it by using the standard syntax for referencing secrets."
    required: false
  PERSONAL_ACCESS_TOKEN: 
    description: "A token you have generated that will be used to access the GitHub API. You have to create it with repo scope and store in the repository's secrets with the name PERSONAL_ACCESS_TOKEN. Paste it by using the standard syntax for referencing secrets."
    required: false
  signature-path:
    description: The path where the signatures will be stored.
    required: false
  signature-branch:
    description: The branch where the signatures will be stored.
    required: false
  signature-remote-repo:
    description: The name of another repository to store the signatures.
    required: false
  signature-remote-owner:
    description: The owner of the remote repository, can be an organization. Leave empty to default to this repository owner.
    required: false
  re-run-path:
    description: The path where the re-run cache will be stored.
    required: false
  re-run-branch:
    description: The branch where the re-run cache will be stored.
    required: false
  form-path:
    description: The document which shall be signed by the contributor(s). Must be an issue form (yml file).
    required: true
  ignore-list:
    description: A list of users that will be ignored when checking for signatures. They are not required for the signature checks to pass. The separator between the patterns is a comma.
    required: false
  re-trigger:
    description: The keyword to re-trigger signature checks.
    required: false
  all-signed-comment:
    description: The posted comment when each committer has signed the document. 
    required: false
  comment-header:
    description: Usually a message thanking the committers and asking them to sign the document.
    required: false
  signed-label:
    description: A label that will be applied once all committers have signed the document
    required: false
  unsigned-label:
    description: A label that will be applied until all committers have signed the document
    required: false
  ignore-label:
    description: Add this label to skip the signature checks
    required: false
  form-label:
    description: The label used to find the document form.
    required: false

runs:
  using: composite
  steps:
    - run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.11.2 2>&1 1>/dev/null
        DENO_INSTALL="$HOME/.deno"
        echo "DENO_INSTALL=$DENO_INSTALL" >> GITHUB_ENV
        echo "$DENO_INSTALL/bin" >> $GITHUB_PATH
      shell: bash
      # INPUT_* environment variables are missing in composite actions https://github.com/actions/runner/issues/665
    - run: |
        deno run -Aq ${{ github.action_path }}/bundle.js \
          --githubToken ${{ inputs.GITHUB_TOKEN }} \
          --personalAccessToken ${{ inputs.PERSONAL_ACCESS_TOKEN }} \
          --signaturePath ${{ inputs.signature-path }} \
          --signatureBranch ${{ inputs.signature-branch }} \
          --signatureRemoteRepo ${{ inputs.signature-remote-repo }} \
          --signatureRemoteOwner ${{ inputs.signature-remote-owner }} \
          --reRunBranch ${{ inputs.re-run-branch }} \
          --reRunPath ${{ inputs.re-run-path }} \
          --formPath ${{ inputs.form-path }} \
          --ignoreList ${{ inputs.ignore-list }} \
          --reTrigger ${{ inputs.re-trigger }} \
          --allSignedComment ${{ inputs.all-signed-comment }} \
          --commentHeader ${{ inputs.comment-header }} \
          --signedLabel ${{ inputs.signed-label }} \
          --unsignedLabel ${{ inputs.unsigned-label }} \
          --ignoreLabel ${{ inputs.ignore-label }} \
          --formLabel ${{ inputs.form-label }}
      shell: bash
