name: "Contributor assistant | CLA"
description: "An action to handle the Contributor License Agreement (CLA)"
author: "SAP"
branding:
  icon: "award"
  color: blue
inputs:
  signatures-path:
    description: "Give a path for storing signatures in a json file "
    required: false
  branch:
    description: "provide a branch where all the signatures are stored"
    required: false
  allowlist:
    description: "users in the allow list don't have to sign the CLA document"
    required: false
  # WIP
runs:
  using: "composite"
  steps:
    - run: |
        version="1.10.3"
        curl -fsSL https://deno.land/x/dvm/install.sh | sh
        source "$HOME/.bash_profile"
        dvm install $version
        deno_install="$HOME/.deno/bin"
        echo $deno_install >> $GITHUB_PATH
      shell: bash
    - run: deno run -Aq ${{ github.action_path }}/../../src/cla-functions/cli.ts --branch ${{ inputs.branch }}
      shell: bash
