
name: "Contributor Assistant"

on:
  pull_request_target:
    types: [opened,reopened,closed,synchronize]
    

jobs:
  Contributor-Assistant:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout my-organization/awesome-action
        uses: actions/checkout@v2
        with:
          repository: cla-assistant/contributor-assistant
          ref: refs/heads/main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_REPO_SCOPE }}
          persist-credentials: false
          
      - name: ask for signature
        uses: ./src/cla

# Background Infos 
# To get a Slack Webhook URL, follow instruction here: https://api.slack.com/messaging/webhooks
# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
