
name: "Contributor Assistant"

on:
  pull_request_target:
    types: [opened,reopened,closed,synchronize]
    

jobs:
  Contributor-Assistant:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout my-organization/awesome-action
        uses: actions/checkout@v2 # this is not needed if the called action is in a different repository
        with:
          repository: cla-assistant/contributor-assistant
          ref: refs/heads/main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_REPO_SCOPE }}
          persist-credentials: false
          
      - name: ask for signature
        uses: ./actions/cla
