name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 9 * * *"

jobs:
  test:
    name: Deno Stable

    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        deno: ["1.11.1", "v1.x", "canary"]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run tests
        run: deno test --allow-net --allow-env
